name: Build and Deploy

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    
    environment:
      name: testing
    env:
      ES_CLOUD_ID: ${{secrets.ES_CLOUD_ID}}
      ES_USERNAME: ${{secrets.ES_USERNAME}}
      ES_PASSWORD: ${{secrets.ES_PASSWORD}}

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        architecture: "x64"
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: install all dependencies
      run: pip install -r requirements.txt
    - name: Start server
      run: |
        uvicorn app.api:app --host 0.0.0.0 --port 8000 &
    - name: Run Tests
      run: pytest -v

  deploy:

    env:
      ES_CLOUD_ID: ${{secrets.ES_CLOUD_ID}}
      ES_USERNAME: ${{secrets.ES_USERNAME}}
      ES_PASSWORD: ${{secrets.ES_PASSWORD}}
      VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}

    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        architecture: "x64"
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: install all dependencies
      run: pip install -r requirements.txt
    - name: Start server
      run: |
        uvicorn app.api:app --host 0.0.0.0 --port 8000 &
    - name: Deploy to vercel
      run: vercel --token $VERCEL_TOKEN
    
    
