name: Test, Build and Push to Docker Hub 

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    
    environment:
      name: testing
    env:
      ES_CLOUD_ID: ${{secrets.ES_CLOUD_ID}}
      ES_USERNAME: ${{secrets.ES_USERNAME}}
      ES_PASSWORD: ${{secrets.ES_PASSWORD}}

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        architecture: "x64"
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: install all dependencies
      run: pip install -r requirements.txt
    - name: Start server
      run: |
        uvicorn app.api:app --host 0.0.0.0 --port 8000 &
    - name: Run Tests
      run: pytest -v

  deploy:

    environment:
      name: production

    env:
      ES_CLOUD_ID: ${{secrets.ES_CLOUD_ID}}
      ES_USERNAME: ${{secrets.ES_USERNAME}}
      ES_PASSWORD: ${{secrets.ES_PASSWORD}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: tests

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: docker build . --file Dockerfile -t $DOCKER_USERNAME/es_app:latest
    - name: Push to Docker Hub
      run: docker push $DOCKER_USERNAME/es_app:latest
    
    
