name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    
    environment:
      name: testing
    env:
      ES_CLOUD_ID: ${{secrets.ES_CLOUD_ID}}
      ES_USERNAME: ${{secrets.ES_USERNAME}}
      ES_PASSWORD: ${{secrets.ES_PASSWORD}}

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: install all dependencies
      run: pip install -r requirements.txt
    - name: Run Tests
      run: pytest -v
